### ISSUE TITLE
Potential deadlock due to preexisting cell colors

### ISSUE THREAD

**Issue by GNiklasch** [eaglgenes101/formic-formation#1]
Whilst watching a handful of random games, with The Formation 1.0.1 participating, I've noticed the following picture arise a few times:
```
+---+---+---+
| * | Q | 3 |
|   | w | w |
+---+---+---+
| 2 | 1 |   |
| r | r |   |
+---+---+---+
| 1 |   | * |
| g |   |   |
+---+---+---+
```
where the numbers indicate worker types, w/r/g stands for white/red/green resp., all other cells in view are white, and the cells marked with an asterisk sometimes contained an enemy worker (though no enemy interference seems to be necessary to result in this situation).
Once in this state, the formation is deadlocked. (Other ants arriving on the scene might later get it unwedged.)
As far as I've been able to see, entering a partially painted area with a single red cell adjacent to a single green cell may be enough to trigger this (but I'm not quite sure about that). I've seen it happen at the edge of a Wildfire desolation, on the Sliding Miners rail, and on a Windmill rail.

**Comment by eaglgenes101** [comment]
I've run on and off into scenarios where the formation ends up deadlocked because the UP_REALIGN signal (red) makes it all the way to the queen. I thought I stamped that out, but apparently it's still there. 

As a stopgap, I'll make it cause a panic if a realign signal makes it to the queen, but this fix is rather unsatisfying, so I'll see if I can prevent it from making it past the bend in the first place.

**Comment by eaglgenes101** [comment]
I've pushed up two changes related to the U_REALIGN signal: 

-  The queen now panics if she finds an U_REALIGN signal makes it all the way to her. 
- Ants in the FOUR_STAIRS configuration refuse to send the U_REALIGN signal at any and all times, preventing the signal from propagating past a bend. 

This should resolve the problem, but testing will need to be done to see if it actually does.

**Comment by eaglgenes101** [comment]
So... unless this issue comes up again, I think it should be safe to say this issue's closed.
